name: Trigger Restriction API for a test account every hour

on:
  schedule:
    # Runs "At minute 0 past every hour." (see https://crontab.guru)
    - cron: '0 */1 * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run script file
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: |
         cd ${GITHUB_WORKSPACE}
         chmod +x ./public/scripts/test.sh
         sh ./public/scripts/test.sh
        shell: bash