name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '* */1 * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Print pwd path
        run: echo pwd

      - name: Print GITHUB_WORKSPACE
        run: echo ${GITHUB_WORKSPACE}  

      - name: Run script file
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: |
         chmod +x ${GITHUB_WORKSPACE}/public/scripts/test.sh
         sh ${GITHUB_WORKSPACE}/public/scripts/test.sh
        shell: bash
